name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      timeout-minutes: 10
      id: astra
      with:
        token: ${{ secrets.TESTS_ASTRA_TOKEN }}
        region: us-east-2
        cloud: aws

    - run: |
        id="${{ steps.astra.outputs.id }}" 
        name="${{ steps.astra.outputs.name }}"
        endpoint="${{ steps.astra.outputs.api-endpoint }}"
        if [ -z "$id" ]; then
          echo "output id not found"
          exit 1
        fi
        if [ -z "$name" ]; then
          echo "output name not found"
          exit 1
        fi
        if [ -z "$endpoint" ]; then
          echo "output endpoint not found"
          exit 1
        fi
    - uses: nicoloboschi/cleanup-astradb@v1
      if: ${{ always() && steps.astra.outputs.name != '' }}
      with:
        token: ${{ secrets.TESTS_ASTRA_TOKEN }}
        name: ${{ steps.astra.outputs.name }}
        wait: false
